QTranConfig = {
    'project': 'StarCraft-II',
    'scenario': '3m',
    'replay_buffer_size': 5000,
    'mixing_embed_dim': 32,
    'rnn_hidden_dim': 64,
    'learning_rate': 0.0005,
    'min_learning_rate': 0.0001,
    'memory_warmup_size': 32,
    'gamma': 0.99,
    'egreedy_exploration': 1.0,
    'min_exploration': 0.1,
    'target_update_interval': 2000,
    'batch_size': 32,
    'total_steps': 1000000,
    'train_log_interval': 5,  # log every 10 episode
    'test_log_interval': 20,  # log every 100 epidode
    'clip_grad_norm': 10,
    'learner_update_freq': 2,
    'double_q': True,
    'opt_loss_coef': 1.0,
    'nopt_min_loss_coef': 0.1,
    'difficulty': '7',
    'algo': 'qtran',
    'log_dir': 'work_dirs/',
    'logger': 'wandb',
}
